// api/gatewayevents/v1/gatewayevents.proto
//
// Per docs/rfcs/2026-09-03-api-gatewayevents-contract.md: the structured
// outcome of one gateway request, joinable to the OTel span that already
// carries gen_ai.*/cost/cache_hit data (see
// docs/rfcs/2026-09-02-otel-tracing-agent-run-id.md) via trace_id/span_id.
// This message never re-encodes anything already real on that span.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gatewayevents/v1/gatewayevents.proto

package gatewayeventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome is derived from the same sentinel errors
// internal/gateway/dataplane already returns — no new rejection
// categories invented beyond what the code already distinguishes.
type GatewayDecisionEvent_Outcome int32

const (
	GatewayDecisionEvent_OUTCOME_UNSPECIFIED       GatewayDecisionEvent_Outcome = 0
	GatewayDecisionEvent_OUTCOME_OK                GatewayDecisionEvent_Outcome = 1
	GatewayDecisionEvent_OUTCOME_AUTH_FAILED       GatewayDecisionEvent_Outcome = 2
	GatewayDecisionEvent_OUTCOME_MODEL_NOT_ALLOWED GatewayDecisionEvent_Outcome = 3
	GatewayDecisionEvent_OUTCOME_RATE_LIMITED      GatewayDecisionEvent_Outcome = 4
	GatewayDecisionEvent_OUTCOME_BUDGET_EXCEEDED   GatewayDecisionEvent_Outcome = 5
	GatewayDecisionEvent_OUTCOME_NO_DEPLOYMENT     GatewayDecisionEvent_Outcome = 6
	GatewayDecisionEvent_OUTCOME_UPSTREAM_ERROR    GatewayDecisionEvent_Outcome = 7
	// Per docs/rfcs/2026-09-03-guardrails-pii-regex-classifier.md: a
	// pre-call or post-call guardrail Block-tier verdict rejected this
	// request. Distinct from OUTCOME_UPSTREAM_ERROR so a guardrail
	// rejection is never misclassified as an upstream failure.
	GatewayDecisionEvent_OUTCOME_GUARDRAIL_BLOCKED GatewayDecisionEvent_Outcome = 8
)

// Enum value maps for GatewayDecisionEvent_Outcome.
var (
	GatewayDecisionEvent_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_OK",
		2: "OUTCOME_AUTH_FAILED",
		3: "OUTCOME_MODEL_NOT_ALLOWED",
		4: "OUTCOME_RATE_LIMITED",
		5: "OUTCOME_BUDGET_EXCEEDED",
		6: "OUTCOME_NO_DEPLOYMENT",
		7: "OUTCOME_UPSTREAM_ERROR",
		8: "OUTCOME_GUARDRAIL_BLOCKED",
	}
	GatewayDecisionEvent_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":       0,
		"OUTCOME_OK":                1,
		"OUTCOME_AUTH_FAILED":       2,
		"OUTCOME_MODEL_NOT_ALLOWED": 3,
		"OUTCOME_RATE_LIMITED":      4,
		"OUTCOME_BUDGET_EXCEEDED":   5,
		"OUTCOME_NO_DEPLOYMENT":     6,
		"OUTCOME_UPSTREAM_ERROR":    7,
		"OUTCOME_GUARDRAIL_BLOCKED": 8,
	}
)

func (x GatewayDecisionEvent_Outcome) Enum() *GatewayDecisionEvent_Outcome {
	p := new(GatewayDecisionEvent_Outcome)
	*p = x
	return p
}

func (x GatewayDecisionEvent_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatewayDecisionEvent_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_gatewayevents_v1_gatewayevents_proto_enumTypes[0].Descriptor()
}

func (GatewayDecisionEvent_Outcome) Type() protoreflect.EnumType {
	return &file_gatewayevents_v1_gatewayevents_proto_enumTypes[0]
}

func (x GatewayDecisionEvent_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatewayDecisionEvent_Outcome.Descriptor instead.
func (GatewayDecisionEvent_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_gatewayevents_v1_gatewayevents_proto_rawDescGZIP(), []int{0, 0}
}

// One per HandleChatCompletion/HandleChatCompletionStream call.
type GatewayDecisionEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TraceId    string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId     string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// virtual_key_id is "" if auth itself failed (no key was resolved).
	VirtualKeyId   string                       `protobuf:"bytes,4,opt,name=virtual_key_id,json=virtualKeyId,proto3" json:"virtual_key_id,omitempty"`
	RequestedModel string                       `protobuf:"bytes,5,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	Outcome        GatewayDecisionEvent_Outcome `protobuf:"varint,6,opt,name=outcome,proto3,enum=gatewayevents.v1.GatewayDecisionEvent_Outcome" json:"outcome,omitempty"`
	// True iff the rate limiter's backend errored for this request and the
	// request was allowed through anyway (fail-open), per
	// docs/rfcs/2026-09-03-distributed-rate-limiting.md's "Fail-open, not
	// fail-closed" section. false covers BOTH "rate limiter ran and did not
	// fail open" and "rate limiter never ran for this request" (an Outcome of
	// OUTCOME_AUTH_FAILED/OUTCOME_MODEL_NOT_ALLOWED means the request never
	// reached the rate-limit check at all) — those two are intentionally not
	// distinguished; cross-reference Outcome for that.
	RateLimitFailOpen bool `protobuf:"varint,7,opt,name=rate_limit_fail_open,json=rateLimitFailOpen,proto3" json:"rate_limit_fail_open,omitempty"`
	// fallback_happened, fallback_from_deployment, and fallback_reason
	// together describe whether this request fell back to a second
	// deployment. Kelvran's fallback logic attempts at most ONE fallback per
	// request, never a chain (gateway/ARCHITECTURE.md's router step) — a
	// fixed 3-field record, not a repeated/list shape.
	FallbackHappened bool `protobuf:"varint,8,opt,name=fallback_happened,json=fallbackHappened,proto3" json:"fallback_happened,omitempty"`
	// Name of the deployment first tried and abandoned. "" when
	// fallback_happened is false. The deployment ULTIMATELY used is not
	// repeated here — it's already derivable from the OTel span's
	// DeploymentName/Provider attributes, joinable via trace_id/span_id, per
	// this message's own "never re-encodes anything already real on that
	// span" rule.
	FallbackFromDeployment string `protobuf:"bytes,9,opt,name=fallback_from_deployment,json=fallbackFromDeployment,proto3" json:"fallback_from_deployment,omitempty"`
	// The first attempt's error (err.Error()). "" when fallback_happened is
	// false. Free text, not an enum — unlike Outcome, these are arbitrary
	// upstream/provider failures with no existing sentinel-error taxonomy.
	FallbackReason string `protobuf:"bytes,10,opt,name=fallback_reason,json=fallbackReason,proto3" json:"fallback_reason,omitempty"`
	// Cumulative USD spend for virtual_key_id at the moment the budget check
	// decided whether to allow this request — i.e. BEFORE this request's own
	// cost (if any) is added. Decimal-as-string, matching
	// docs/rfcs/2026-09-02-decimal-cost-accounting.md's convention. "0" is a
	// real, meaningful value (a key that has genuinely spent nothing yet),
	// not a "field absent" sentinel — only meaningful when the budget check
	// actually ran; cross-reference Outcome (OUTCOME_AUTH_FAILED/
	// OUTCOME_MODEL_NOT_ALLOWED/OUTCOME_RATE_LIMITED all precede the budget
	// check and never populate this field).
	BudgetSpentUsd string `protobuf:"bytes,11,opt,name=budget_spent_usd,json=budgetSpentUsd,proto3" json:"budget_spent_usd,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayDecisionEvent) Reset() {
	*x = GatewayDecisionEvent{}
	mi := &file_gatewayevents_v1_gatewayevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayDecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayDecisionEvent) ProtoMessage() {}

func (x *GatewayDecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayevents_v1_gatewayevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayDecisionEvent.ProtoReflect.Descriptor instead.
func (*GatewayDecisionEvent) Descriptor() ([]byte, []int) {
	return file_gatewayevents_v1_gatewayevents_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayDecisionEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GatewayDecisionEvent) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *GatewayDecisionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *GatewayDecisionEvent) GetVirtualKeyId() string {
	if x != nil {
		return x.VirtualKeyId
	}
	return ""
}

func (x *GatewayDecisionEvent) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

func (x *GatewayDecisionEvent) GetOutcome() GatewayDecisionEvent_Outcome {
	if x != nil {
		return x.Outcome
	}
	return GatewayDecisionEvent_OUTCOME_UNSPECIFIED
}

func (x *GatewayDecisionEvent) GetRateLimitFailOpen() bool {
	if x != nil {
		return x.RateLimitFailOpen
	}
	return false
}

func (x *GatewayDecisionEvent) GetFallbackHappened() bool {
	if x != nil {
		return x.FallbackHappened
	}
	return false
}

func (x *GatewayDecisionEvent) GetFallbackFromDeployment() string {
	if x != nil {
		return x.FallbackFromDeployment
	}
	return ""
}

func (x *GatewayDecisionEvent) GetFallbackReason() string {
	if x != nil {
		return x.FallbackReason
	}
	return ""
}

func (x *GatewayDecisionEvent) GetBudgetSpentUsd() string {
	if x != nil {
		return x.BudgetSpentUsd
	}
	return ""
}

var File_gatewayevents_v1_gatewayevents_proto protoreflect.FileDescriptor

const file_gatewayevents_v1_gatewayevents_proto_rawDesc = "" +
	"\n" +
	"$gatewayevents/v1/gatewayevents.proto\x12\x10gatewayevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x06\n" +
	"\x14GatewayDecisionEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12$\n" +
	"\x0evirtual_key_id\x18\x04 \x01(\tR\fvirtualKeyId\x12'\n" +
	"\x0frequested_model\x18\x05 \x01(\tR\x0erequestedModel\x12H\n" +
	"\aoutcome\x18\x06 \x01(\x0e2..gatewayevents.v1.GatewayDecisionEvent.OutcomeR\aoutcome\x12/\n" +
	"\x14rate_limit_fail_open\x18\a \x01(\bR\x11rateLimitFailOpen\x12+\n" +
	"\x11fallback_happened\x18\b \x01(\bR\x10fallbackHappened\x128\n" +
	"\x18fallback_from_deployment\x18\t \x01(\tR\x16fallbackFromDeployment\x12'\n" +
	"\x0ffallback_reason\x18\n" +
	" \x01(\tR\x0efallbackReason\x12(\n" +
	"\x10budget_spent_usd\x18\v \x01(\tR\x0ebudgetSpentUsd\"\xf7\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"OUTCOME_OK\x10\x01\x12\x17\n" +
	"\x13OUTCOME_AUTH_FAILED\x10\x02\x12\x1d\n" +
	"\x19OUTCOME_MODEL_NOT_ALLOWED\x10\x03\x12\x18\n" +
	"\x14OUTCOME_RATE_LIMITED\x10\x04\x12\x1b\n" +
	"\x17OUTCOME_BUDGET_EXCEEDED\x10\x05\x12\x19\n" +
	"\x15OUTCOME_NO_DEPLOYMENT\x10\x06\x12\x1a\n" +
	"\x16OUTCOME_UPSTREAM_ERROR\x10\a\x12\x1d\n" +
	"\x19OUTCOME_GUARDRAIL_BLOCKED\x10\bBIZGgithub.com/kelvran/gateway/gateway/api/gatewayevents/v1;gatewayeventsv1b\x06proto3"

var (
	file_gatewayevents_v1_gatewayevents_proto_rawDescOnce sync.Once
	file_gatewayevents_v1_gatewayevents_proto_rawDescData []byte
)

func file_gatewayevents_v1_gatewayevents_proto_rawDescGZIP() []byte {
	file_gatewayevents_v1_gatewayevents_proto_rawDescOnce.Do(func() {
		file_gatewayevents_v1_gatewayevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gatewayevents_v1_gatewayevents_proto_rawDesc), len(file_gatewayevents_v1_gatewayevents_proto_rawDesc)))
	})
	return file_gatewayevents_v1_gatewayevents_proto_rawDescData
}

var file_gatewayevents_v1_gatewayevents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gatewayevents_v1_gatewayevents_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gatewayevents_v1_gatewayevents_proto_goTypes = []any{
	(GatewayDecisionEvent_Outcome)(0), // 0: gatewayevents.v1.GatewayDecisionEvent.Outcome
	(*GatewayDecisionEvent)(nil),      // 1: gatewayevents.v1.GatewayDecisionEvent
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_gatewayevents_v1_gatewayevents_proto_depIdxs = []int32{
	2, // 0: gatewayevents.v1.GatewayDecisionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 1: gatewayevents.v1.GatewayDecisionEvent.outcome:type_name -> gatewayevents.v1.GatewayDecisionEvent.Outcome
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gatewayevents_v1_gatewayevents_proto_init() }
func file_gatewayevents_v1_gatewayevents_proto_init() {
	if File_gatewayevents_v1_gatewayevents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gatewayevents_v1_gatewayevents_proto_rawDesc), len(file_gatewayevents_v1_gatewayevents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gatewayevents_v1_gatewayevents_proto_goTypes,
		DependencyIndexes: file_gatewayevents_v1_gatewayevents_proto_depIdxs,
		EnumInfos:         file_gatewayevents_v1_gatewayevents_proto_enumTypes,
		MessageInfos:      file_gatewayevents_v1_gatewayevents_proto_msgTypes,
	}.Build()
	File_gatewayevents_v1_gatewayevents_proto = out.File
	file_gatewayevents_v1_gatewayevents_proto_goTypes = nil
	file_gatewayevents_v1_gatewayevents_proto_depIdxs = nil
}
