// Package adapter defines the canonical request/response schema shared by
// every provider adapter (OpenAI, Anthropic, Gemini, Bedrock, openaicompat)
// plus the Adapter interface each of them implements.
//
// The canonical schema is OpenAI Chat-Completions-shaped, per
// gateway/ARCHITECTURE.md's "Canonical Schema & Provider Adapters" section.
// Every adapter's ToProvider/FromProvider pair is responsible for the four
// documented normalization hazards described there: tool-call argument
// encoding, system-prompt placement, streaming event shape, and
// unknown-field preservation.
package adapter

import "encoding/json"

// Message is one turn in a canonical chat conversation. Its JSON shape is
// Kelvran's own client-facing wire format — OpenAI Chat-Completions-shaped,
// per gateway/ARCHITECTURE.md, since the canonical schema doubles as the
// gateway's own inbound/outbound API surface, not just an internal type.
type Message struct {
	// Role is one of "system", "user", "assistant", or "tool".
	Role string `json:"role"`
	// Content is the message's text content. For assistant messages that
	// only carry tool calls, Content may be empty. Unchanged by Parts
	// below — a multi-modal message may still carry lead-in text here.
	Content string `json:"content,omitempty"`
	// Parts, when non-empty, is this message's multi-modal content —
	// image/document parts alongside (or instead of) Content — per
	// docs/rfcs/2026-09-06-gateway-multimodal-content.md. Deliberately
	// additive: Content's own type is unchanged, so every existing
	// call site across every adapter/dataplane/test keeps working
	// exactly as before for the common, Parts-empty, text-only case.
	Parts []ContentPart `json:"parts,omitempty"`
	// ToolCalls holds any tool/function calls the assistant requested in
	// this message. Empty for non-assistant messages.
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	// ToolCallID identifies which prior ToolCall this message is a result
	// for. Only set on role:"tool" messages.
	ToolCallID string `json:"tool_call_id,omitempty"`
	// CacheControl, when set, opts this whole message into provider-side
	// prompt caching, per
	// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md. Nil (the
	// default) is a silent no-op for every adapter -- it never changes
	// what's forwarded, only whether a caching marker rides alongside it.
	CacheControl *CacheControl `json:"cache_control,omitempty"`
	// Refusal, when non-empty, is the model's own explanation for
	// declining to comply with the request -- OpenAI's real, current
	// response-message shape carries this as a field SIBLING to Content
	// (never inside it), confirmed against OpenAI's own official Node SDK
	// source (openai-node's ChatCompletionMessage.refusal: "The refusal
	// message generated by the model.", always present, possibly null).
	// Response-only: no adapter ever reads this on the request/ToProvider
	// path, since no provider's request-message shape accepts it.
	// Anthropic/Gemini/Bedrock have no equivalent field at all -- each
	// already signals an analogous condition through its own
	// finish_reason mapping instead (Anthropic's stop_reason "refusal" ->
	// "content_filter"; Gemini's finishReason SAFETY/PROHIBITED_CONTENT/
	// etc.; Bedrock's stopReason "guardrail_intervened"/
	// "content_filtered") -- those three adapters leave this field
	// permanently empty, a silent no-op matching every other optional
	// field's convention in this schema. Empty (the default, and every
	// Message built before this field existed) means either no refusal
	// occurred, or the serving adapter has no native equivalent to
	// surface.
	Refusal string `json:"refusal,omitempty"`
}

// ContentPart is one piece of a multi-modal message's content, per
// docs/rfcs/2026-09-06-gateway-multimodal-content.md.
type ContentPart struct {
	// Type is "text", "image", or "document".
	Type string `json:"type"`
	// Text is set when Type == "text".
	Text string `json:"text,omitempty"`
	// MediaType is the MIME type (e.g. "image/png", "application/pdf"),
	// set when Type != "text".
	MediaType string `json:"media_type,omitempty"`
	// Data is base64-encoded inline content. Mutually exclusive with
	// URL — exactly one of the two is set when Type != "text".
	Data string `json:"data,omitempty"`
	// URL is a remote reference passed through to the provider
	// verbatim — Kelvran itself never fetches it.
	URL string `json:"url,omitempty"`
	// CacheControl, when set, opts this specific part into provider-side
	// prompt caching independently of its parent Message's own
	// CacheControl, per
	// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md. Nil (the
	// default) is a silent no-op for every adapter.
	CacheControl *CacheControl `json:"cache_control,omitempty"`
}

// CacheControl is an opt-in marker requesting provider-side prompt
// caching for the message or content-part it's attached to, per
// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md. A nil
// CacheControl (the default on every Message/ContentPart) is a silent
// no-op for every adapter — it changes nothing about how the request is
// forwarded, matching this schema's existing optional-field convention
// (ContentPart/Parts's own additive, no-op-when-empty precedent from
// docs/rfcs/2026-09-06-gateway-multimodal-content.md).
type CacheControl struct {
	// TTL requests a non-default cache lifetime. Only Anthropic (direct,
	// and Bedrock's Anthropic-family cachePoint) reads this — "" means
	// that provider's own default (5 minutes); "1h" opts into the
	// longer, more expensive lifetime both document. Every other
	// provider/model family ignores TTL as a no-op, never an error,
	// since neither Bedrock's non-Anthropic families nor OpenAI expose
	// an equivalent per-breakpoint TTL knob.
	TTL string `json:"ttl,omitempty"`
	// Key is a stable, caller-supplied identity (e.g. a session or
	// conversation ID) that only OpenAI's adapter reads, to set its
	// top-level prompt_cache_key routing hint — see
	// internal/adapter/openai's ToProvider doc comment for why Kelvran
	// never invents this value itself. Ignored (a no-op) by every other
	// adapter.
	Key string `json:"key,omitempty"`
}

// ToolCall is a single tool/function invocation requested by the model.
//
// ArgumentsJSON is always a JSON-encoded string in the canonical schema,
// even though some providers (Anthropic, Gemini, Bedrock) hand back an
// already-parsed object natively — adapters are responsible for
// marshaling/unmarshaling at the boundary so the canonical type stays
// consistent across every provider. ToolCall implements a custom
// MarshalJSON/UnmarshalJSON pair so its *wire* shape still matches
// OpenAI's real tool_calls[].function.{name,arguments} nesting, even
// though the Go struct itself stays flat for adapters' convenience.
type ToolCall struct {
	ID            string
	Name          string
	ArgumentsJSON string
}

type toolCallWire struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	Function struct {
		Name      string `json:"name"`
		Arguments string `json:"arguments"`
	} `json:"function"`
}

// MarshalJSON implements json.Marshaler, producing OpenAI's native
// tool_calls[] element shape.
func (t ToolCall) MarshalJSON() ([]byte, error) {
	var w toolCallWire
	w.ID = t.ID
	w.Type = "function"
	w.Function.Name = t.Name
	w.Function.Arguments = t.ArgumentsJSON
	return json.Marshal(w)
}

// UnmarshalJSON implements json.Unmarshaler, parsing OpenAI's native
// tool_calls[] element shape back into the flat canonical fields.
func (t *ToolCall) UnmarshalJSON(data []byte) error {
	var w toolCallWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	t.ID = w.ID
	t.Name = w.Function.Name
	t.ArgumentsJSON = w.Function.Arguments
	return nil
}

// ToolDef describes a tool/function the model is allowed to call. Like
// ToolCall, it carries a custom JSON (de)serialization pair so the wire
// shape matches OpenAI's native tools[].function.{name,description,
// parameters} nesting.
type ToolDef struct {
	Name        string
	Description string
	// ParametersJSON is the tool's JSON Schema parameter definition,
	// encoded as a string for the same reason ToolCall.ArgumentsJSON is.
	ParametersJSON string
	// CacheControl, when set, opts this specific tool definition into
	// provider-side prompt caching, per
	// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md's
	// tool-definition-level addendum. Nil (the default) is a silent
	// no-op for every adapter, matching Message/ContentPart's own
	// CacheControl convention.
	CacheControl *CacheControl
	// Strict, when true, opts this specific tool's input schema into
	// strict grammar-backed validation. Anthropic's own docs confirm this
	// shares the same grammar mechanism as
	// ChatRequest.ResponseFormat's output_config.format, and is an
	// independently-composable per-tool flag, not a global one. Read only
	// by the Anthropic and Bedrock adapters (both translate it onto their
	// native Tool's own sibling "strict" key, mirroring CacheControl's
	// placement); OpenAI/openaicompat/Gemini never read this field at all
	// in v1, a named scope limit (OpenAI's own per-tool "strict" flag is
	// deliberately deferred, not wired). False (the default) is a silent
	// no-op for every adapter.
	Strict bool
}

type toolDefWire struct {
	Type     string `json:"type"`
	Function struct {
		Name        string          `json:"name"`
		Description string          `json:"description,omitempty"`
		Parameters  json.RawMessage `json:"parameters,omitempty"`
	} `json:"function"`
	// CacheControl sits as a sibling of Type/Function, not nested inside
	// Function -- the same "additive marker alongside the provider-native
	// shape" convention Message.CacheControl already established (a
	// sibling of Role/Content).
	CacheControl *CacheControl `json:"cache_control,omitempty"`
	// Strict mirrors CacheControl's own sibling-of-Type/Function
	// placement -- the wire-level counterpart of ToolDef.Strict above.
	Strict bool `json:"strict,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (t ToolDef) MarshalJSON() ([]byte, error) {
	var w toolDefWire
	w.Type = "function"
	w.Function.Name = t.Name
	w.Function.Description = t.Description
	if t.ParametersJSON != "" {
		w.Function.Parameters = json.RawMessage(t.ParametersJSON)
	}
	w.CacheControl = t.CacheControl
	w.Strict = t.Strict
	return json.Marshal(w)
}

// UnmarshalJSON implements json.Unmarshaler.
func (t *ToolDef) UnmarshalJSON(data []byte) error {
	var w toolDefWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	t.Name = w.Function.Name
	t.Description = w.Function.Description
	if len(w.Function.Parameters) > 0 {
		t.ParametersJSON = string(w.Function.Parameters)
	}
	t.CacheControl = w.CacheControl
	t.Strict = w.Strict
	return nil
}

// ResponseFormat requests structured, schema-conforming JSON output from
// the model. Nil (the default) is a silent no-op for every adapter, matching
// CacheControl's own "unset is a no-op" convention. Type is always
// "json_schema" in v1 -- the canonical schema names no other value, and
// this mirrors both Anthropic's and OpenAI's own top-level
// discriminator field.
//
// v1 is request-shape normalization only: no JSON Schema validation
// library exists in this module's go.mod/go.sum, and none is added by
// this feature -- a provider with no NATIVE schema-enforcement mechanism
// of its own simply gets no v1 support for this field (see
// adapter.SupportsStructuredOutput), never a client-side re-validation
// fallback.
type ResponseFormat struct {
	Type string `json:"type"`
	// JSONSchema carries the schema itself, set whenever Type ==
	// "json_schema".
	JSONSchema *JSONSchema `json:"json_schema,omitempty"`
}

// JSONSchema is the schema payload carried by a ResponseFormat.
type JSONSchema struct {
	// Name identifies the schema -- required by OpenAI's and Anthropic's
	// own real wire shapes alike.
	Name string `json:"name"`
	// Strict, when true, requests the provider's strictest grammar-backed
	// enforcement of Schema, mirroring ToolDef.Strict's own per-tool flag
	// but scoped to the response format itself.
	Strict bool `json:"strict,omitempty"`
	// Schema is the raw JSON Schema document. Kept as json.RawMessage,
	// never parsed or validated by Kelvran itself -- this feature is
	// request-shape normalization only (see ResponseFormat's own doc
	// comment).
	Schema json.RawMessage `json:"schema"`
}

// ChatRequest is the canonical, provider-agnostic chat completion request.
type ChatRequest struct {
	Model       string    `json:"model"`
	Messages    []Message `json:"messages"`
	Temperature *float64  `json:"temperature,omitempty"`
	MaxTokens   *int      `json:"max_tokens,omitempty"`
	Tools       []ToolDef `json:"tools,omitempty"`
	Stream      bool      `json:"stream,omitempty"`
	// ResponseFormat, when set, requests structured JSON output
	// conforming to a caller-supplied schema. Nil (the default, and every
	// ChatRequest built before this field existed) is a silent no-op --
	// byte-identical to today's existing behavior.
	ResponseFormat *ResponseFormat `json:"response_format,omitempty"`
	// DisableCacheControlAutoPopulate, when true, suppresses the
	// Anthropic and Bedrock adapters' auto-population of a default
	// CacheControl marker on an otherwise-unmarked system message, per
	// docs/rfcs/2026-09-07-gateway-cache-control-auto-populate.md.
	// dataplane sets this from the resolved Deployment's own
	// DisableCacheControlAutoPopulate config field immediately before
	// calling ToProvider -- the same per-call override pattern
	// Deployment.UpstreamModel already uses for Model, since a
	// deployment-scoped policy has nowhere else to live given
	// ToProvider's single-parameter, pure-function signature (see that
	// RFC's own "why ChatRequest, not the Adapter interface" section).
	// json:"-" is deliberate: ChatRequest doubles as Kelvran's own
	// client-facing wire format (chatCompletionsHandler unmarshals a
	// request body directly into this type), and this field expresses an
	// OPERATOR's deployment-level policy, never a per-call client
	// choice -- json:"-" makes it structurally unreachable from a
	// request body, not merely undocumented. False (the zero value, and
	// every ChatRequest built before this field existed) means
	// auto-populate stays ON, matching this schema's own "zero value
	// preserves prior behavior" convention.
	DisableCacheControlAutoPopulate bool `json:"-"`
	// PromptID, when set, names a server-side prompt/template (see
	// internal/prompt) to resolve into real Messages content at the
	// gateway, before routing -- per this feature's own global,
	// operator-managed design (the same category as price_table/
	// deployments/guardrails config), any virtual key may reference any
	// PromptID; there is no per-key ownership/authorization concept.
	// Empty (the default, and every ChatRequest built before this field
	// existed) is a silent no-op -- PromptVersion/PromptVariables below
	// are meaningless without it.
	PromptID string `json:"prompt_id,omitempty"`
	// PromptVersion pins PromptID to a specific historical version;
	// <= 0 (the default) means "the latest version at resolution time."
	// Meaningless when PromptID == "".
	PromptVersion int `json:"prompt_version,omitempty"`
	// PromptVariables supplies the {{name}} substitution values
	// internal/prompt.Store.Resolve applies to PromptID's stored
	// content. Meaningless when PromptID == "".
	PromptVariables map[string]string `json:"prompt_variables,omitempty"`
}

// Usage is token accounting for a single completion. PromptTokens is the
// TOTAL input-token count charged for this request, per each provider's
// own definition -- it ALREADY INCLUDES CacheReadTokens/CacheCreationTokens
// below. Anthropic's own confirmed formula: total_input_tokens =
// cache_read_input_tokens + cache_creation_input_tokens + input_tokens
// (verified live against platform.claude.com/docs/en/api/messages).
// Bedrock's Converse API TokenUsage.totalTokens is documented as "the
// total of input tokens and tokens generated by the model" -- i.e.
// inputTokens+outputTokens ONLY (verified live against the AWS API
// reference), so cache tokens must be added on top there too.
// TotalTokens = PromptTokens + CompletionTokens, unchanged.
type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
	// CacheReadTokens is the subset of PromptTokens served from the
	// provider's prompt cache (Anthropic cache_read_input_tokens / Bedrock
	// cacheReadInputTokens) -- priced well below a fresh prompt token.
	// Zero when no cache read occurred. Informational only for
	// token-counting purposes (already folded into PromptTokens above) --
	// exists so costaccounting.Calculate can price this slice at its own
	// optional rate.
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// CacheCreationTokens is the subset of PromptTokens spent writing a
	// NEW cache entry (Anthropic cache_creation_input_tokens / Bedrock
	// cacheWriteInputTokens) -- priced ABOVE a fresh prompt token for
	// Anthropic. Zero when no cache write occurred.
	CacheCreationTokens int `json:"cache_creation_tokens,omitempty"`
}

// Choice is a single generated completion candidate.
type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
}

// ChatResponse is the canonical, provider-agnostic chat completion response.
type ChatResponse struct {
	ID      string   `json:"id"`
	Model   string   `json:"model"`
	Choices []Choice `json:"choices"`
	Usage   Usage    `json:"usage"`
}

// Adapter translates between the canonical schema above and one upstream
// provider's native wire format. Implementations must be pure functions:
// no network calls, no hidden state beyond what's passed in.
type Adapter interface {
	// ToProvider converts a canonical request into the provider's native
	// request shape. The returned value's concrete type is
	// provider-specific (e.g. an OpenAI-native or Anthropic-native
	// request struct) and is opaque to callers outside the adapter.
	ToProvider(ChatRequest) (any, error)
	// FromProvider converts a provider-native response (the same concrete
	// type ToProvider's caller would send upstream and get back) into the
	// canonical response shape.
	FromProvider(any) (ChatResponse, error)
	// Name identifies the adapter (e.g. "openai", "anthropic").
	Name() string
}
