// Package adapter defines the canonical request/response schema shared by
// every provider adapter (OpenAI, Anthropic, Gemini, Bedrock, openaicompat)
// plus the Adapter interface each of them implements.
//
// The canonical schema is OpenAI Chat-Completions-shaped, per
// gateway/ARCHITECTURE.md's "Canonical Schema & Provider Adapters" section.
// Every adapter's ToProvider/FromProvider pair is responsible for the four
// documented normalization hazards described there: tool-call argument
// encoding, system-prompt placement, streaming event shape, and
// unknown-field preservation.
package adapter

import (
	"encoding/json"
	"fmt"
)

// Message is one turn in a canonical chat conversation. Its JSON shape is
// Kelvran's own client-facing wire format — OpenAI Chat-Completions-shaped,
// per gateway/ARCHITECTURE.md, since the canonical schema doubles as the
// gateway's own inbound/outbound API surface, not just an internal type.
type Message struct {
	// Role is one of "system", "user", "assistant", or "tool".
	Role string `json:"role"`
	// Content is the message's text content. For assistant messages that
	// only carry tool calls, Content may be empty. Unchanged by Parts
	// below — a multi-modal message may still carry lead-in text here.
	Content string `json:"content,omitempty"`
	// Parts, when non-empty, is this message's multi-modal content —
	// image/document parts alongside (or instead of) Content — per
	// docs/rfcs/2026-09-06-gateway-multimodal-content.md. Deliberately
	// additive: Content's own type is unchanged, so every existing
	// call site across every adapter/dataplane/test keeps working
	// exactly as before for the common, Parts-empty, text-only case.
	Parts []ContentPart `json:"parts,omitempty"`
	// ToolCalls holds any tool/function calls the assistant requested in
	// this message. Empty for non-assistant messages.
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`
	// ToolCallID identifies which prior ToolCall this message is a result
	// for. Only set on role:"tool" messages.
	ToolCallID string `json:"tool_call_id,omitempty"`
	// CacheControl, when set, opts this whole message into provider-side
	// prompt caching, per
	// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md. Nil (the
	// default) is a silent no-op for every adapter -- it never changes
	// what's forwarded, only whether a caching marker rides alongside it.
	CacheControl *CacheControl `json:"cache_control,omitempty"`
	// Refusal, when non-empty, is the model's own explanation for
	// declining to comply with the request -- OpenAI's real, current
	// response-message shape carries this as a field SIBLING to Content
	// (never inside it), confirmed against OpenAI's own official Node SDK
	// source (openai-node's ChatCompletionMessage.refusal: "The refusal
	// message generated by the model.", always present, possibly null).
	// Response-only: no adapter ever reads this on the request/ToProvider
	// path, since no provider's request-message shape accepts it.
	// Anthropic/Gemini/Bedrock have no equivalent field at all -- each
	// already signals an analogous condition through its own
	// finish_reason mapping instead (Anthropic's stop_reason "refusal" ->
	// "content_filter"; Gemini's finishReason SAFETY/PROHIBITED_CONTENT/
	// etc.; Bedrock's stopReason "guardrail_intervened"/
	// "content_filtered") -- those three adapters leave this field
	// permanently empty, a silent no-op matching every other optional
	// field's convention in this schema. Empty (the default, and every
	// Message built before this field existed) means either no refusal
	// occurred, or the serving adapter has no native equivalent to
	// surface.
	Refusal string `json:"refusal,omitempty"`
	// ReasoningBlocks holds this assistant turn's ordered chain-of-thought/
	// extended-thinking blocks, per
	// docs/rfcs/2026-09-12-gateway-reasoning-content-canonical-schema.md.
	// Each block is OPAQUE -- Kelvran never interprets, restructures, or
	// generates its content -- and callers MUST echo the exact slice
	// (unmodified, in order) back on any subsequent ChatRequest.Messages
	// entry carrying this same assistant turn, or Anthropic/Bedrock's
	// Claude Messages API returns a hard 400. Position relative to
	// ToolCalls is preserved via each block's own Sequence field, since
	// Claude 4's interleaved-thinking mode can place multiple reasoning
	// blocks between multiple tool calls within one turn. Empty (the
	// default, and every Message built before this field existed) is a
	// silent no-op for every adapter, matching Parts/CacheControl's own
	// convention.
	ReasoningBlocks []ReasoningBlock `json:"reasoning_blocks,omitempty"`
}

// ReasoningBlock is one opaque reasoning/thinking block, per
// docs/rfcs/2026-09-12-gateway-reasoning-content-canonical-schema.md.
type ReasoningBlock struct {
	// Sequence is this block's position within the turn, using the same
	// index space as Message.ToolCalls: a value of N means "immediately
	// before ToolCalls[N]" (N >= len(ToolCalls) means "after all tool
	// calls"). Required to reconstruct exact original block order for
	// Claude 4's interleaved-thinking mode.
	Sequence int `json:"sequence"`
	// Redacted marks this block as provider-encrypted/opaque ciphertext
	// (Anthropic redacted_thinking, Bedrock redactedContent) -- Kelvran
	// MUST NOT attempt to interpret, scan, log, or fingerprint its
	// contents when true; treat Data as an inert byte string.
	Redacted bool `json:"redacted,omitempty"`
	// Text is the plaintext reasoning content when Redacted is false
	// (Anthropic thinking.thinking, Bedrock reasoningText.text). Empty
	// when Redacted is true.
	Text string `json:"text,omitempty"`
	// Data is the opaque ciphertext payload when Redacted is true
	// (Anthropic redacted_thinking.data, Bedrock redactedContent).
	Data string `json:"data,omitempty"`
	// Signature is the provider-issued cryptographic signature
	// authenticating Text's plaintext (Anthropic thinking.signature,
	// Bedrock reasoningText.signature) -- opaque, must be replayed
	// verbatim alongside Text.
	Signature string `json:"signature,omitempty"`
}

// ContentPart is one piece of a multi-modal message's content, per
// docs/rfcs/2026-09-06-gateway-multimodal-content.md.
type ContentPart struct {
	// Type is "text", "image", or "document".
	Type string `json:"type"`
	// Text is set when Type == "text".
	Text string `json:"text,omitempty"`
	// MediaType is the MIME type (e.g. "image/png", "application/pdf"),
	// set when Type != "text".
	MediaType string `json:"media_type,omitempty"`
	// Data is base64-encoded inline content. Mutually exclusive with
	// URL — exactly one of the two is set when Type != "text".
	Data string `json:"data,omitempty"`
	// URL is a remote reference passed through to the provider
	// verbatim — Kelvran itself never fetches it.
	URL string `json:"url,omitempty"`
	// CacheControl, when set, opts this specific part into provider-side
	// prompt caching independently of its parent Message's own
	// CacheControl, per
	// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md. Nil (the
	// default) is a silent no-op for every adapter.
	CacheControl *CacheControl `json:"cache_control,omitempty"`
}

// CacheControl is an opt-in marker requesting provider-side prompt
// caching for the message or content-part it's attached to, per
// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md. A nil
// CacheControl (the default on every Message/ContentPart) is a silent
// no-op for every adapter — it changes nothing about how the request is
// forwarded, matching this schema's existing optional-field convention
// (ContentPart/Parts's own additive, no-op-when-empty precedent from
// docs/rfcs/2026-09-06-gateway-multimodal-content.md).
type CacheControl struct {
	// TTL requests a non-default cache lifetime. Only Anthropic (direct,
	// and Bedrock's Anthropic-family cachePoint) reads this — "" means
	// that provider's own default (5 minutes); "1h" opts into the
	// longer, more expensive lifetime both document. Every other
	// provider/model family ignores TTL as a no-op, never an error,
	// since neither Bedrock's non-Anthropic families nor OpenAI expose
	// an equivalent per-breakpoint TTL knob.
	TTL string `json:"ttl,omitempty"`
	// Key is a stable, caller-supplied identity (e.g. a session or
	// conversation ID) that only OpenAI's adapter reads, to set its
	// top-level prompt_cache_key routing hint — see
	// internal/adapter/openai's ToProvider doc comment for why Kelvran
	// never invents this value itself. Ignored (a no-op) by every other
	// adapter.
	Key string `json:"key,omitempty"`
}

// ToolCall is a single tool/function invocation requested by the model.
//
// ArgumentsJSON is always a JSON-encoded string in the canonical schema,
// even though some providers (Anthropic, Gemini, Bedrock) hand back an
// already-parsed object natively — adapters are responsible for
// marshaling/unmarshaling at the boundary so the canonical type stays
// consistent across every provider. ToolCall implements a custom
// MarshalJSON/UnmarshalJSON pair so its *wire* shape still matches
// OpenAI's real tool_calls[].function.{name,arguments} nesting, even
// though the Go struct itself stays flat for adapters' convenience.
type ToolCall struct {
	ID            string
	Name          string
	ArgumentsJSON string
}

type toolCallWire struct {
	ID       string `json:"id"`
	Type     string `json:"type"`
	Function struct {
		Name      string `json:"name"`
		Arguments string `json:"arguments"`
	} `json:"function"`
}

// MarshalJSON implements json.Marshaler, producing OpenAI's native
// tool_calls[] element shape.
func (t ToolCall) MarshalJSON() ([]byte, error) {
	var w toolCallWire
	w.ID = t.ID
	w.Type = "function"
	w.Function.Name = t.Name
	w.Function.Arguments = t.ArgumentsJSON
	return json.Marshal(w)
}

// UnmarshalJSON implements json.Unmarshaler, parsing OpenAI's native
// tool_calls[] element shape back into the flat canonical fields.
func (t *ToolCall) UnmarshalJSON(data []byte) error {
	var w toolCallWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	t.ID = w.ID
	t.Name = w.Function.Name
	t.ArgumentsJSON = w.Function.Arguments
	return nil
}

// ToolDef describes a tool/function the model is allowed to call. Like
// ToolCall, it carries a custom JSON (de)serialization pair so the wire
// shape matches OpenAI's native tools[].function.{name,description,
// parameters} nesting.
type ToolDef struct {
	Name        string
	Description string
	// ParametersJSON is the tool's JSON Schema parameter definition,
	// encoded as a string for the same reason ToolCall.ArgumentsJSON is.
	ParametersJSON string
	// CacheControl, when set, opts this specific tool definition into
	// provider-side prompt caching, per
	// docs/rfcs/2026-09-07-gateway-provider-prompt-caching.md's
	// tool-definition-level addendum. Nil (the default) is a silent
	// no-op for every adapter, matching Message/ContentPart's own
	// CacheControl convention.
	CacheControl *CacheControl
	// Strict, when true, opts this specific tool's input schema into
	// strict grammar-backed validation. Anthropic's own docs confirm this
	// shares the same grammar mechanism as
	// ChatRequest.ResponseFormat's output_config.format, and is an
	// independently-composable per-tool flag, not a global one. Read by
	// the Anthropic, OpenAI, openaicompat, AND Bedrock adapters (each
	// translates it onto their native tool definition's own sibling
	// "strict" key). Corrected 2026-09-22: two prior "deliberately
	// deferred, not wired" scope limits are now closed. OpenAI's real
	// Structured Outputs feature genuinely has a per-function "strict"
	// wire field (confirmed against OpenAI's own API), wired in both
	// openai.FunctionDef and openaicompat.FunctionDef. Bedrock Converse's
	// toolSpec also genuinely has a "strict" sibling key (confirmed
	// against AWS's own ML blog and the AWS SDK for Python/Ruby's
	// ToolSpecification type reference), wired in bedrock.ToolSpec. Only
	// Gemini never reads this field at all. False (the default) is a
	// silent no-op for every adapter.
	Strict bool
}

type toolDefWire struct {
	Type     string `json:"type"`
	Function struct {
		Name        string          `json:"name"`
		Description string          `json:"description,omitempty"`
		Parameters  json.RawMessage `json:"parameters,omitempty"`
	} `json:"function"`
	// CacheControl sits as a sibling of Type/Function, not nested inside
	// Function -- the same "additive marker alongside the provider-native
	// shape" convention Message.CacheControl already established (a
	// sibling of Role/Content).
	CacheControl *CacheControl `json:"cache_control,omitempty"`
	// Strict mirrors CacheControl's own sibling-of-Type/Function
	// placement -- the wire-level counterpart of ToolDef.Strict above.
	Strict bool `json:"strict,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (t ToolDef) MarshalJSON() ([]byte, error) {
	var w toolDefWire
	w.Type = "function"
	w.Function.Name = t.Name
	w.Function.Description = t.Description
	if t.ParametersJSON != "" {
		w.Function.Parameters = json.RawMessage(t.ParametersJSON)
	}
	w.CacheControl = t.CacheControl
	w.Strict = t.Strict
	return json.Marshal(w)
}

// UnmarshalJSON implements json.Unmarshaler.
func (t *ToolDef) UnmarshalJSON(data []byte) error {
	var w toolDefWire
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	t.Name = w.Function.Name
	t.Description = w.Function.Description
	if len(w.Function.Parameters) > 0 {
		t.ParametersJSON = string(w.Function.Parameters)
	}
	t.CacheControl = w.CacheControl
	t.Strict = w.Strict
	return nil
}

// ResponseFormat requests structured, schema-conforming JSON output from
// the model. Nil (the default) is a silent no-op for every adapter, matching
// CacheControl's own "unset is a no-op" convention. Type is always
// "json_schema" in v1 -- the canonical schema names no other value, and
// this mirrors both Anthropic's and OpenAI's own top-level
// discriminator field.
//
// v1 is request-shape normalization only: no JSON Schema validation
// library exists in this module's go.mod/go.sum, and none is added by
// this feature -- a provider with no NATIVE schema-enforcement mechanism
// of its own simply gets no v1 support for this field (see
// adapter.SupportsStructuredOutput), never a client-side re-validation
// fallback.
type ResponseFormat struct {
	Type string `json:"type"`
	// JSONSchema carries the schema itself, set whenever Type ==
	// "json_schema".
	JSONSchema *JSONSchema `json:"json_schema,omitempty"`
}

// JSONSchema is the schema payload carried by a ResponseFormat.
type JSONSchema struct {
	// Name identifies the schema -- required by OpenAI's and Anthropic's
	// own real wire shapes alike.
	Name string `json:"name"`
	// Strict, when true, requests the provider's strictest grammar-backed
	// enforcement of Schema, mirroring ToolDef.Strict's own per-tool flag
	// but scoped to the response format itself.
	Strict bool `json:"strict,omitempty"`
	// Schema is the raw JSON Schema document. Kept as json.RawMessage,
	// never parsed or validated by Kelvran itself -- this feature is
	// request-shape normalization only (see ResponseFormat's own doc
	// comment).
	Schema json.RawMessage `json:"schema"`
}

// ChatRequest is the canonical, provider-agnostic chat completion request.
type ChatRequest struct {
	Model       string    `json:"model"`
	Messages    []Message `json:"messages"`
	Temperature *float64  `json:"temperature,omitempty"`
	MaxTokens   *int      `json:"max_tokens,omitempty"`
	Tools       []ToolDef `json:"tools,omitempty"`
	Stream      bool      `json:"stream,omitempty"`
	// ResponseFormat, when set, requests structured JSON output
	// conforming to a caller-supplied schema. Nil (the default, and every
	// ChatRequest built before this field existed) is a silent no-op --
	// byte-identical to today's existing behavior.
	ResponseFormat *ResponseFormat `json:"response_format,omitempty"`
	// DisableCacheControlAutoPopulate, when true, suppresses the
	// Anthropic and Bedrock adapters' auto-population of a default
	// CacheControl marker on an otherwise-unmarked system message, per
	// docs/rfcs/2026-09-07-gateway-cache-control-auto-populate.md.
	// dataplane sets this from the resolved Deployment's own
	// DisableCacheControlAutoPopulate config field immediately before
	// calling ToProvider -- the same per-call override pattern
	// Deployment.UpstreamModel already uses for Model, since a
	// deployment-scoped policy has nowhere else to live given
	// ToProvider's single-parameter, pure-function signature (see that
	// RFC's own "why ChatRequest, not the Adapter interface" section).
	// json:"-" is deliberate: ChatRequest doubles as Kelvran's own
	// client-facing wire format (chatCompletionsHandler unmarshals a
	// request body directly into this type), and this field expresses an
	// OPERATOR's deployment-level policy, never a per-call client
	// choice -- json:"-" makes it structurally unreachable from a
	// request body, not merely undocumented. False (the zero value, and
	// every ChatRequest built before this field existed) means
	// auto-populate stays ON, matching this schema's own "zero value
	// preserves prior behavior" convention.
	DisableCacheControlAutoPopulate bool `json:"-"`
	// PromptID, when set, names a server-side prompt/template (see
	// internal/prompt) to resolve into real Messages content at the
	// gateway, before routing -- per this feature's own global,
	// operator-managed design (the same category as price_table/
	// deployments/guardrails config), any virtual key may reference any
	// PromptID; there is no per-key ownership/authorization concept.
	// Empty (the default, and every ChatRequest built before this field
	// existed) is a silent no-op -- PromptVersion/PromptVariables below
	// are meaningless without it.
	PromptID string `json:"prompt_id,omitempty"`
	// PromptVersion pins PromptID to a specific historical version;
	// <= 0 (the default) means "the latest version at resolution time."
	// Meaningless when PromptID == "". Mutually exclusive with
	// PromptLabel below -- setting both is a real client error (see
	// ErrPromptLabelAndVersionBothSet).
	PromptVersion int `json:"prompt_version,omitempty"`
	// PromptLabel resolves PromptID to whichever version a named,
	// operator-mutable label (internal/prompt.Store.SetLabel) currently
	// points at, e.g. "production" -- the promote/rollback primitive: an
	// operator moves the label server-side, and every client already
	// requesting that label starts serving the new version with no
	// client-side change at all. Empty (the default, and every
	// ChatRequest built before this field existed) means no label
	// resolution -- PromptVersion's own plain-integer-pin behavior
	// applies instead. Meaningless when PromptID == "".
	PromptLabel string `json:"prompt_label,omitempty"`
	// PromptVariables supplies the {{name}} substitution values
	// internal/prompt.Store.Resolve applies to PromptID's stored
	// content. Meaningless when PromptID == "".
	PromptVariables map[string]string `json:"prompt_variables,omitempty"`
	// ToolChoice, when set, requests tool-calling forcing behavior --
	// per docs/rfcs/2026-09-14-gateway-tool-choice-normalization.md. Nil
	// (the default, and every ChatRequest built before this field
	// existed) is a silent no-op for every adapter, matching
	// ResponseFormat/CacheControl's own established "unset is a no-op"
	// convention -- each provider's own default ("auto": the model
	// decides) applies.
	ToolChoice *ToolChoice `json:"tool_choice,omitempty"`
	// ThinkingBindingMode controls how Anthropic's preserved-thinking
	// prefix-integrity check (the thinking-binding-controls-2026-08-01
	// beta feature) handles a replayed thinking/redacted_thinking block
	// whose signed prefix (the system prompt/tools/messages sent before
	// it) no longer matches what's being sent now -- see the addendum to
	// docs/rfcs/2026-09-12-gateway-reasoning-content-canonical-schema.md
	// for the full reachability analysis: Kelvran's own prompt
	// management (docs/rfcs/2026-09-13-gateway-prompt-management.md) is
	// global and live-mutable, so an admin editing or version-bumping a
	// prompt template between the turn a thinking block was signed under
	// and the turn it's replayed on can invalidate that exact prefix
	// through no fault of the caller.
	//
	// One of "" (default), "non_strict", or "strict":
	//
	//   - "" (the default, and every ChatRequest built before this
	//     field existed): Kelvran requests Anthropic's NON-STRICT mode
	//     ("drop_block") -- deliberately the OPPOSITE of Anthropic's own
	//     strict-by-default behavior for accounts created on or after
	//     2026-08-31. This divergence is intentional, not an oversight:
	//     Kelvran has no mechanism to guarantee prefix stability across
	//     turns given its own live-mutable global prompt design, so
	//     inheriting Anthropic's strict default would let an ordinary
	//     admin prompt edit silently break an in-flight reasoning
	//     conversation with an opaque 400 that isn't the caller's own
	//     mistake.
	//   - "non_strict": the explicit spelling of the default above.
	//   - "strict": opts into Anthropic's own default ("error") instead,
	//     for callers who want a hard reasoning-continuity guarantee and
	//     would rather fail loudly than silently lose a thinking block.
	//
	// Meaningless -- a silent no-op -- for every provider/model that
	// doesn't run this check at all, which today is every Anthropic
	// model except the two named in anthropic.go's own model gate, and
	// every non-Anthropic provider.
	ThinkingBindingMode string `json:"thinking_binding_mode,omitempty"`
}

// ToolChoice requests forcing behavior for tool calling, per
// docs/rfcs/2026-09-14-gateway-tool-choice-normalization.md.
type ToolChoice struct {
	// Mode is one of "auto" (provider default, model decides), "required"
	// (must call at least one tool, provider decides which), "none"
	// (must not call a tool), or "tool" (must call the specific tool
	// named by ToolName). Required whenever ToolChoice is non-nil.
	Mode string `json:"mode"`
	// ToolName names the specific tool to force -- read only when
	// Mode == "tool"; ignored otherwise.
	ToolName string `json:"tool_name,omitempty"`
	// DisableParallelToolUse, when true, requests at most one tool call
	// even under Mode "auto"/"required". Only Anthropic's own direct
	// Messages API has a confirmed native equivalent
	// (tool_choice.disable_parallel_tool_use) -- AWS's own Converse API
	// reference documents no equivalent flag on ToolChoice's union type,
	// so Bedrock (including Bedrock's Anthropic-family models) ignores
	// this too. Every adapter besides direct Anthropic ignores this as a
	// no-op, the same "provider/model family ignores as a no-op, never
	// an error" convention CacheControl.TTL already established.
	DisableParallelToolUse bool `json:"disable_parallel_tool_use,omitempty"`
}

// Usage is token accounting for a single completion. PromptTokens is the
// TOTAL input-token count charged for this request, per each provider's
// own definition -- it ALREADY INCLUDES CacheReadTokens/CacheCreationTokens
// below. Anthropic's own confirmed formula: total_input_tokens =
// cache_read_input_tokens + cache_creation_input_tokens + input_tokens
// (verified live against platform.claude.com/docs/en/api/messages).
// Bedrock's Converse API TokenUsage.totalTokens is documented as "the
// total of input tokens and tokens generated by the model" -- i.e.
// inputTokens+outputTokens ONLY (verified live against the AWS API
// reference), so cache tokens must be added on top there too.
// TotalTokens = PromptTokens + CompletionTokens, unchanged.
type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
	// CacheReadTokens is the subset of PromptTokens served from the
	// provider's prompt cache (Anthropic cache_read_input_tokens / Bedrock
	// cacheReadInputTokens) -- priced well below a fresh prompt token.
	// Zero when no cache read occurred. Informational only for
	// token-counting purposes (already folded into PromptTokens above) --
	// exists so costaccounting.Calculate can price this slice at its own
	// optional rate.
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// CacheCreationTokens is the subset of PromptTokens spent writing a
	// NEW cache entry (Anthropic cache_creation_input_tokens / Bedrock
	// cacheWriteInputTokens) -- priced ABOVE a fresh prompt token for
	// Anthropic. Zero when no cache write occurred.
	CacheCreationTokens int `json:"cache_creation_tokens,omitempty"`
}

// Choice is a single generated completion candidate.
type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
}

// ChatResponse is the canonical, provider-agnostic chat completion response.
type ChatResponse struct {
	ID      string   `json:"id"`
	Model   string   `json:"model"`
	Choices []Choice `json:"choices"`
	Usage   Usage    `json:"usage"`
	// InputTransformations reports thinking/redacted_thinking blocks
	// Anthropic's preserved-thinking prefix-integrity check dropped, or
	// let through despite failing, on THIS call -- per the
	// thinking-binding-controls-2026-08-01 addendum to
	// docs/rfcs/2026-09-12-gateway-reasoning-content-canonical-schema.md
	// (see ChatRequest.ThinkingBindingMode's own doc comment for the
	// full context). Anthropic-only: nil on every response from every
	// other adapter (no equivalent check exists elsewhere today), and
	// nil on Anthropic responses too whenever the request's model didn't
	// match anthropic.go's own model gate -- a silent no-op matching
	// Refusal's own per-provider-availability convention. Non-empty only
	// when at least one block was actually affected.
	InputTransformations []InputTransformation `json:"input_transformations,omitempty"`
}

// InputTransformation is one entry in Anthropic's own top-level
// input_transformations response array, per ChatResponse.
// InputTransformations' own doc comment. Live-verified against
// platform.claude.com/docs/en/build-with-claude/preserved-thinking
// (2026-09-24).
type InputTransformation struct {
	// Type is "thinking_dropped" (the block never reached the model and
	// wasn't billed) or "thinking_mismatch_allowed" (the block failed
	// the prefix check but reached the model anyway, because this
	// request/account doesn't enforce the check by default -- an
	// older-account compatibility signal Anthropic never emits for a
	// request that set prefix_mismatch_behavior explicitly, which this
	// adapter always does for every model its own gate names).
	Type string `json:"type"`
	// Path names the affected block's location in the request, verbatim
	// from Anthropic's own wire shape (e.g. "messages.3.content.0") --
	// opaque, never parsed or interpreted by Kelvran.
	Path string `json:"path"`
	// Reason is "prefix_binding_mismatch" (the live-mutable-prompt
	// reachability risk this whole feature exists to surface) or
	// "model_binding_mismatch" (the block was produced by a model the
	// serving model can't read).
	Reason string `json:"reason"`
}

// Adapter translates between the canonical schema above and one upstream
// provider's native wire format. Implementations must be pure functions:
// no network calls, no hidden state beyond what's passed in.
type Adapter interface {
	// ToProvider converts a canonical request into the provider's native
	// request shape. The returned value's concrete type is
	// provider-specific (e.g. an OpenAI-native or Anthropic-native
	// request struct) and is opaque to callers outside the adapter.
	ToProvider(ChatRequest) (any, error)
	// FromProvider converts a provider-native response (the same concrete
	// type ToProvider's caller would send upstream and get back) into the
	// canonical response shape.
	FromProvider(any) (ChatResponse, error)
	// Name identifies the adapter (e.g. "openai", "anthropic").
	Name() string
}

// EmbeddingRequest is the canonical, provider-agnostic embeddings
// request — deliberately its own type, never a retrofit of ChatRequest,
// per this codebase's own established additive-capability convention
// (Parts/CacheControl/ReasoningBlocks/ToolChoice were all added as new
// types/fields, never by repurposing an existing one for a second
// meaning).
type EmbeddingRequest struct {
	// Model is the canonical model name a Deployment with Kind ==
	// "embedding" resolves to routing — same convention as
	// ChatRequest.Model.
	Model string `json:"model"`
	// Input is one or more texts to embed. A single string is the
	// common case; multiple strings amortize one upstream round trip
	// across a batch, mirroring OpenAI's own real "input: string |
	// string[]" contract. The Go field is always []string (multiple
	// entries is the more general shape every EmbeddingAdapter and
	// dataplane.Pipeline.HandleEmbeddings already iterate over) --
	// UnmarshalJSON below is what actually accepts a bare JSON string on
	// the wire and normalizes it into a single-element slice, closing a
	// real gap an audit found: this field's own doc comment already
	// claimed the dual "string | string[]" contract, but before
	// UnmarshalJSON existed, a bare JSON string was rejected outright
	// with a raw "cannot unmarshal string into []string" error, never
	// reaching this package's translation logic at all.
	Input []string `json:"input"`
	// Dimensions optionally requests a reduced output embedding size —
	// both real providers this package supports accept this today:
	// OpenAI's text-embedding-3-* models truncate/re-normalize their
	// native dimensionality on request (confirmed against OpenAI's own
	// current API reference), and Bedrock Titan V2 accepts one of
	// {256, 512, 1024} (confirmed live; see bedrock.EmbeddingRequest's
	// own doc comment, which used to hardcode this to 1024 with no
	// caller-facing knob at all). Zero means "unset" — each provider
	// adapter falls back to its own existing default (1024 for Titan,
	// the model's native dimensionality for OpenAI, via omitempty)
	// rather than a value this package invents, so a caller that never
	// sets this sees byte-identical behavior to before this field
	// existed.
	Dimensions int `json:"dimensions,omitempty"`
}

// embeddingRequestWire mirrors EmbeddingRequest's own JSON tags, except
// Input stays raw here so UnmarshalJSON can try both real shapes before
// deciding which one the wire payload actually used.
type embeddingRequestWire struct {
	Model      string          `json:"model"`
	Input      json.RawMessage `json:"input"`
	Dimensions int             `json:"dimensions,omitempty"`
}

// UnmarshalJSON accepts Input as either a bare JSON string or a JSON
// array of strings -- see Input's own doc comment for why this exists.
// An array is tried first (the more common multi-entry case for this
// package's own callers); a bare string is normalized into a single-
// element slice. Anything else (a number, object, array of non-strings,
// etc.) is a real error, not silently coerced.
func (r *EmbeddingRequest) UnmarshalJSON(data []byte) error {
	var wire embeddingRequestWire
	if err := json.Unmarshal(data, &wire); err != nil {
		return err
	}
	r.Model = wire.Model
	r.Dimensions = wire.Dimensions

	if len(wire.Input) == 0 {
		r.Input = nil
		return nil
	}
	var asSlice []string
	if err := json.Unmarshal(wire.Input, &asSlice); err == nil {
		r.Input = asSlice
		return nil
	}
	var asString string
	if err := json.Unmarshal(wire.Input, &asString); err != nil {
		return fmt.Errorf("adapter: EmbeddingRequest.Input must be a string or an array of strings: %w", err)
	}
	r.Input = []string{asString}
	return nil
}

// EmbeddingResponse is the canonical, provider-agnostic embeddings
// response.
type EmbeddingResponse struct {
	Model string `json:"model"`
	// Data holds one embedding vector per EmbeddingRequest.Input entry,
	// in the same order.
	Data []EmbeddingData `json:"data"`
	// Usage.CompletionTokens is always zero for an embeddings response —
	// there is no completion, only input tokenization — reusing the
	// shared Usage type regardless so costaccounting.Calculate's
	// existing PromptTokens-priced-per-model logic applies with zero
	// changes.
	Usage Usage `json:"usage"`
}

// EmbeddingData is one embedding vector, indexed to its EmbeddingRequest
// input position.
type EmbeddingData struct {
	Index     int       `json:"index"`
	Embedding []float64 `json:"embedding"`
}

// EmbeddingAdapter translates between the canonical embeddings schema
// above and one upstream provider's native wire format. Deliberately a
// SEPARATE interface from Adapter, not an extra method appended to it —
// every provider package implementing Adapter would otherwise need a
// dummy/panicking implementation of an operation it doesn't support
// (Anthropic has no native embeddings model at all; see
// docs/upgrade-research/api-surface-expansion-2026-09-15.md). A
// provider's own *Adapter concrete type may implement BOTH interfaces
// (openai/bedrock do); Registry stores every value as the Adapter
// interface, so a caller wanting embeddings support type-asserts to
// EmbeddingAdapter at the call site (see dataplane.Pipeline.HandleEmbeddings).
type EmbeddingAdapter interface {
	ToEmbeddingProvider(EmbeddingRequest) (any, error)
	FromEmbeddingProvider(any) (EmbeddingResponse, error)
}
